package com.exam;
// Generated May 18, 2019 7:29:39 PM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int id;
     private String name;
     private String price;
     private String qty;
     private String total;

    public Orders() {
    }

	
    public Orders(int id) {
        this.id = id;
    }
    public Orders(int id, String name, String price, String qty, String total) {
       this.id = id;
       this.name = name;
       this.price = price;
       this.qty = qty;
       this.total = total;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


